// COPIED FROM https://a2a-protocol.org/latest/definitions/ and then removed unused parts.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/a2a/extension/history/v1/a2a.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines the possible lifecycle states of a Task.
type TaskState int32

const (
	// The task is in an unknown or indeterminate state.
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	// Represents the status that acknowledges a task is created.
	TaskState_TASK_STATE_SUBMITTED TaskState = 1
	// Represents the status that a task is actively being processed.
	TaskState_TASK_STATE_WORKING TaskState = 2
	// Represents the status a task is finished. This is a terminal state.
	TaskState_TASK_STATE_COMPLETED TaskState = 3
	// Represents the status a task is done but failed. This is a terminal state.
	TaskState_TASK_STATE_FAILED TaskState = 4
	// Represents the status a task was canceled before it finished.
	// This is a terminal state.
	TaskState_TASK_STATE_CANCELED TaskState = 5
	// Represents the status that the task requires information to complete.
	// This is an interrupted state.
	TaskState_TASK_STATE_INPUT_REQUIRED TaskState = 6
	// Represents the status that the agent has decided to not perform the task.
	// This may be done during initial task creation or later once an agent
	// has determined it can't or won't proceed. This is a terminal state.
	TaskState_TASK_STATE_REJECTED TaskState = 7
	// Represents the state that some authentication is needed from the upstream
	// client. This is an interrupted state. Authentication is expected to come out-of-band.
	TaskState_TASK_STATE_AUTH_REQUIRED TaskState = 8
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SUBMITTED",
		2: "TASK_STATE_WORKING",
		3: "TASK_STATE_COMPLETED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_CANCELED",
		6: "TASK_STATE_INPUT_REQUIRED",
		7: "TASK_STATE_REJECTED",
		8: "TASK_STATE_AUTH_REQUIRED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED":    0,
		"TASK_STATE_SUBMITTED":      1,
		"TASK_STATE_WORKING":        2,
		"TASK_STATE_COMPLETED":      3,
		"TASK_STATE_FAILED":         4,
		"TASK_STATE_CANCELED":       5,
		"TASK_STATE_INPUT_REQUIRED": 6,
		"TASK_STATE_REJECTED":       7,
		"TASK_STATE_AUTH_REQUIRED":  8,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_a2a_extension_history_v1_a2a_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_alis_a2a_extension_history_v1_a2a_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{0}
}

// Defines the sender of a message in A2A protocol communication.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	// USER role refers to communication from the client to the server.
	Role_ROLE_USER Role = 1
	// AGENT role refers to communication from the server to the client.
	Role_ROLE_AGENT Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_AGENT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_AGENT":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_a2a_extension_history_v1_a2a_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_alis_a2a_extension_history_v1_a2a_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{1}
}

// Task is the core unit of action for A2A. It has a current status
// and when results are created for the task they are stored in the
// artifact. If there are multiple turns for a task, these are stored in
// history.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (e.g. UUID) for the task, generated by the server for a
	// new task.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique identifier (e.g. UUID) for the contextual collection of interactions
	// (tasks and messages). Created by the A2A server.
	ContextId string `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The current status of a Task, including state and a message.
	Status *TaskStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// A set of output artifacts for a Task.
	Artifacts []*Artifact `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
	// The history of interactions from a task.
	History []*Message `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	// protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
	// A key/value object to store custom metadata about a task.
	Metadata      *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Task) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// A container for the status of a task
type TaskStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current state of this task.
	State TaskState `protobuf:"varint,1,opt,name=state,proto3,enum=alis.a2a.extension.history.v1.TaskState" json:"state,omitempty"`
	// A message associated with the status.
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ISO 8601 Timestamp when the status was recorded.
	// Example: "2023-10-27T10:00:00Z"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *TaskStatus) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskStatus) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TaskStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Part represents a container for a section of communication content.
// Parts can be purely textual, some sort of file (image, video, etc) or
// a structured data blob (i.e. JSON).
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Part_Text
	//	*Part_Raw
	//	*Part_Url
	//	*Part_Data
	Content isPart_Content `protobuf_oneof:"content"`
	// Optional metadata associated with this part.
	Metadata *structpb.Struct `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// An optional name for the file (e.g., "document.pdf").
	Filename string `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	// The media type (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
	// This field is available for all part types.
	MediaType     string `protobuf:"bytes,7,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *Part) GetContent() isPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Content.(*Part_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Part) GetUrl() string {
	if x != nil {
		if x, ok := x.Content.(*Part_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *Part) GetData() *structpb.Value {
	if x != nil {
		if x, ok := x.Content.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Part) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Part) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Part) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type isPart_Content interface {
	isPart_Content()
}

type Part_Text struct {
	// The string content of the text part.
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_Raw struct {
	// The raw byte content of a file. In JSON serialization, this is encoded as a base64 string.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

type Part_Url struct {
	// A URL pointing to the file's content.
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

type Part_Data struct {
	// Arbitrary structured data as a JSON value (object, array, string, number, boolean, or null).
	Data *structpb.Value `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Part_Text) isPart_Content() {}

func (*Part_Raw) isPart_Content() {}

func (*Part_Url) isPart_Content() {}

func (*Part_Data) isPart_Content() {}

// Message is one unit of communication between client and server. It can be
// associated with a context and/or a task. For server messages, context_id must
// be provided, and task_id only if a task was created. For client messages, both
// fields are optional, with the caveat that if both are provided, they have to
// match (the context_id has to be the one that is set on the task). If only
// task_id is provided, the server will infer context_id from it.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier (e.g. UUID) of the message. This is required and
	// created by the message creator.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The context id of the message. This is optional and if set, the message
	// will be associated with the given context.
	ContextId string `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The task id of the message. This is optional and if set, the message
	// will be associated with the given task.
	TaskId string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Identifies the sender of the message.
	Role Role `protobuf:"varint,4,opt,name=role,proto3,enum=alis.a2a.extension.history.v1.Role" json:"role,omitempty"`
	// protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
	// Parts is the container of the message content.
	Parts []*Part `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`
	// protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
	// Any optional metadata to provide along with the message.
	Metadata *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The URIs of extensions that are present or contributed to this Message.
	Extensions []string `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// A list of task IDs that this message references for additional context.
	ReferenceTaskIds []string `protobuf:"bytes,8,rep,name=reference_task_ids,json=referenceTaskIds,proto3" json:"reference_task_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Message) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Message) GetReferenceTaskIds() []string {
	if x != nil {
		return x.ReferenceTaskIds
	}
	return nil
}

// Artifacts represent task outputs.
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (e.g. UUID) for the artifact. It must be at least unique
	// within a task.
	ArtifactId string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// A human readable name for the artifact.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// A human readable description of the artifact, optional.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The content of the artifact. Must contain at least one part.
	Parts []*Part `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`
	// Optional metadata included with the artifact.
	Metadata *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The URIs of extensions that are present or contributed to this Artifact.
	Extensions    []string `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artifact) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Artifact) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// An event sent by the agent to notify the client of a change in a task's
// status.
type TaskStatusUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the task that is changed
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The id of the context that the task belongs to
	ContextId string `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The new status of the task.
	Status *TaskStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Optional metadata to associate with the task update.
	Metadata      *structpb.Struct `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdateEvent) Reset() {
	*x = TaskStatusUpdateEvent{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdateEvent) ProtoMessage() {}

func (x *TaskStatusUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdateEvent) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatusUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdateEvent) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskStatusUpdateEvent) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskStatusUpdateEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskArtifactUpdateEvent represents a task delta where an artifact has
// been generated.
type TaskArtifactUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the task for this artifact.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The id of the context that this task belongs to.
	ContextId string `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// The artifact that was generated or updated.
	Artifact *Artifact `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	// If true, the content of this artifact should be appended to a previously
	// sent artifact with the same ID.
	Append bool `protobuf:"varint,4,opt,name=append,proto3" json:"append,omitempty"`
	// If true, this is the final chunk of the artifact.
	LastChunk bool `protobuf:"varint,5,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"`
	// Optional metadata associated with the artifact update.
	Metadata      *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskArtifactUpdateEvent) Reset() {
	*x = TaskArtifactUpdateEvent{}
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskArtifactUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskArtifactUpdateEvent) ProtoMessage() {}

func (x *TaskArtifactUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskArtifactUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskArtifactUpdateEvent) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *TaskArtifactUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskArtifactUpdateEvent) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskArtifactUpdateEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *TaskArtifactUpdateEvent) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

func (x *TaskArtifactUpdateEvent) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

func (x *TaskArtifactUpdateEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_alis_a2a_extension_history_v1_a2a_proto protoreflect.FileDescriptor

const file_alis_a2a_extension_history_v1_a2a_proto_rawDesc = "" +
	"\n" +
	"'alis/a2a/extension/history/v1/a2a.proto\x12\x1dalis.a2a.extension.history.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\x04Task\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id\x12#\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tcontextId\x12G\n" +
	"\x06status\x18\x03 \x01(\v2).alis.a2a.extension.history.v1.TaskStatusB\x04\xe2A\x01\x02R\x06status\x12E\n" +
	"\tartifacts\x18\x04 \x03(\v2'.alis.a2a.extension.history.v1.ArtifactR\tartifacts\x12@\n" +
	"\ahistory\x18\x05 \x03(\v2&.alis.a2a.extension.history.v1.MessageR\ahistory\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xce\x01\n" +
	"\n" +
	"TaskStatus\x12D\n" +
	"\x05state\x18\x01 \x01(\x0e2(.alis.a2a.extension.history.v1.TaskStateB\x04\xe2A\x01\x02R\x05state\x12@\n" +
	"\amessage\x18\x02 \x01(\v2&.alis.a2a.extension.history.v1.MessageR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xed\x01\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x12\n" +
	"\x03raw\x18\x02 \x01(\fH\x00R\x03raw\x12\x12\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x12,\n" +
	"\x04data\x18\x04 \x01(\v2\x16.google.protobuf.ValueH\x00R\x04data\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"media_type\x18\a \x01(\tR\tmediaTypeB\t\n" +
	"\acontent\"\xe9\x02\n" +
	"\aMessage\x12#\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tmessageId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12=\n" +
	"\x04role\x18\x04 \x01(\x0e2#.alis.a2a.extension.history.v1.RoleB\x04\xe2A\x01\x02R\x04role\x12?\n" +
	"\x05parts\x18\x05 \x03(\v2#.alis.a2a.extension.history.v1.PartB\x04\xe2A\x01\x02R\x05parts\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\x12,\n" +
	"\x12reference_task_ids\x18\b \x03(\tR\x10referenceTaskIds\"\xfd\x01\n" +
	"\bArtifact\x12%\n" +
	"\vartifact_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12?\n" +
	"\x05parts\x18\x05 \x03(\v2#.alis.a2a.extension.history.v1.PartB\x04\xe2A\x01\x02R\x05parts\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\"\xdf\x01\n" +
	"\x15TaskStatusUpdateEvent\x12\x1d\n" +
	"\atask_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06taskId\x12#\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tcontextId\x12G\n" +
	"\x06status\x18\x03 \x01(\v2).alis.a2a.extension.history.v1.TaskStatusB\x04\xe2A\x01\x02R\x06status\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadataJ\x04\b\x04\x10\x05\"\x94\x02\n" +
	"\x17TaskArtifactUpdateEvent\x12\x1d\n" +
	"\atask_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06taskId\x12#\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tcontextId\x12I\n" +
	"\bartifact\x18\x03 \x01(\v2'.alis.a2a.extension.history.v1.ArtifactB\x04\xe2A\x01\x02R\bartifact\x12\x16\n" +
	"\x06append\x18\x04 \x01(\bR\x06append\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x05 \x01(\bR\tlastChunk\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata*\xf9\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SUBMITTED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_WORKING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\x05\x12\x1d\n" +
	"\x19TASK_STATE_INPUT_REQUIRED\x10\x06\x12\x17\n" +
	"\x13TASK_STATE_REJECTED\x10\a\x12\x1c\n" +
	"\x18TASK_STATE_AUTH_REQUIRED\x10\b*;\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_AGENT\x10\x02BGZEgithub.com/alis-exchange/a2a-history-go/alis/a2a/extension/history/v1b\x06proto3"

var (
	file_alis_a2a_extension_history_v1_a2a_proto_rawDescOnce sync.Once
	file_alis_a2a_extension_history_v1_a2a_proto_rawDescData []byte
)

func file_alis_a2a_extension_history_v1_a2a_proto_rawDescGZIP() []byte {
	file_alis_a2a_extension_history_v1_a2a_proto_rawDescOnce.Do(func() {
		file_alis_a2a_extension_history_v1_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_a2a_proto_rawDesc), len(file_alis_a2a_extension_history_v1_a2a_proto_rawDesc)))
	})
	return file_alis_a2a_extension_history_v1_a2a_proto_rawDescData
}

var file_alis_a2a_extension_history_v1_a2a_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alis_a2a_extension_history_v1_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_alis_a2a_extension_history_v1_a2a_proto_goTypes = []any{
	(TaskState)(0),                  // 0: alis.a2a.extension.history.v1.TaskState
	(Role)(0),                       // 1: alis.a2a.extension.history.v1.Role
	(*Task)(nil),                    // 2: alis.a2a.extension.history.v1.Task
	(*TaskStatus)(nil),              // 3: alis.a2a.extension.history.v1.TaskStatus
	(*Part)(nil),                    // 4: alis.a2a.extension.history.v1.Part
	(*Message)(nil),                 // 5: alis.a2a.extension.history.v1.Message
	(*Artifact)(nil),                // 6: alis.a2a.extension.history.v1.Artifact
	(*TaskStatusUpdateEvent)(nil),   // 7: alis.a2a.extension.history.v1.TaskStatusUpdateEvent
	(*TaskArtifactUpdateEvent)(nil), // 8: alis.a2a.extension.history.v1.TaskArtifactUpdateEvent
	(*structpb.Struct)(nil),         // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*structpb.Value)(nil),          // 11: google.protobuf.Value
}
var file_alis_a2a_extension_history_v1_a2a_proto_depIdxs = []int32{
	3,  // 0: alis.a2a.extension.history.v1.Task.status:type_name -> alis.a2a.extension.history.v1.TaskStatus
	6,  // 1: alis.a2a.extension.history.v1.Task.artifacts:type_name -> alis.a2a.extension.history.v1.Artifact
	5,  // 2: alis.a2a.extension.history.v1.Task.history:type_name -> alis.a2a.extension.history.v1.Message
	9,  // 3: alis.a2a.extension.history.v1.Task.metadata:type_name -> google.protobuf.Struct
	0,  // 4: alis.a2a.extension.history.v1.TaskStatus.state:type_name -> alis.a2a.extension.history.v1.TaskState
	5,  // 5: alis.a2a.extension.history.v1.TaskStatus.message:type_name -> alis.a2a.extension.history.v1.Message
	10, // 6: alis.a2a.extension.history.v1.TaskStatus.timestamp:type_name -> google.protobuf.Timestamp
	11, // 7: alis.a2a.extension.history.v1.Part.data:type_name -> google.protobuf.Value
	9,  // 8: alis.a2a.extension.history.v1.Part.metadata:type_name -> google.protobuf.Struct
	1,  // 9: alis.a2a.extension.history.v1.Message.role:type_name -> alis.a2a.extension.history.v1.Role
	4,  // 10: alis.a2a.extension.history.v1.Message.parts:type_name -> alis.a2a.extension.history.v1.Part
	9,  // 11: alis.a2a.extension.history.v1.Message.metadata:type_name -> google.protobuf.Struct
	4,  // 12: alis.a2a.extension.history.v1.Artifact.parts:type_name -> alis.a2a.extension.history.v1.Part
	9,  // 13: alis.a2a.extension.history.v1.Artifact.metadata:type_name -> google.protobuf.Struct
	3,  // 14: alis.a2a.extension.history.v1.TaskStatusUpdateEvent.status:type_name -> alis.a2a.extension.history.v1.TaskStatus
	9,  // 15: alis.a2a.extension.history.v1.TaskStatusUpdateEvent.metadata:type_name -> google.protobuf.Struct
	6,  // 16: alis.a2a.extension.history.v1.TaskArtifactUpdateEvent.artifact:type_name -> alis.a2a.extension.history.v1.Artifact
	9,  // 17: alis.a2a.extension.history.v1.TaskArtifactUpdateEvent.metadata:type_name -> google.protobuf.Struct
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_alis_a2a_extension_history_v1_a2a_proto_init() }
func file_alis_a2a_extension_history_v1_a2a_proto_init() {
	if File_alis_a2a_extension_history_v1_a2a_proto != nil {
		return
	}
	file_alis_a2a_extension_history_v1_a2a_proto_msgTypes[2].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_Raw)(nil),
		(*Part_Url)(nil),
		(*Part_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_a2a_proto_rawDesc), len(file_alis_a2a_extension_history_v1_a2a_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_a2a_extension_history_v1_a2a_proto_goTypes,
		DependencyIndexes: file_alis_a2a_extension_history_v1_a2a_proto_depIdxs,
		EnumInfos:         file_alis_a2a_extension_history_v1_a2a_proto_enumTypes,
		MessageInfos:      file_alis_a2a_extension_history_v1_a2a_proto_msgTypes,
	}.Build()
	File_alis_a2a_extension_history_v1_a2a_proto = out.File
	file_alis_a2a_extension_history_v1_a2a_proto_goTypes = nil
	file_alis_a2a_extension_history_v1_a2a_proto_depIdxs = nil
}
