// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/a2a/extension/history/v1/a2a.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-02-19 14:45:51 UTC

package v1

const ()
