// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/a2a/extension/history/v1/history.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-03 09:11:21 UTC

package v1

const (
	// A2AHistoryService_GetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.GetIamPolicy method.
	A2AHistoryService_GetIamPolicy_FullMethodDescription = "Gets the IAM policy for a resource implemented in this service."
	// A2AHistoryService_SetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.SetIamPolicy method.
	A2AHistoryService_SetIamPolicy_FullMethodDescription = "Sets the IAM policy for a resource implemented in this service."
	// A2AHistoryService_TestIamPermissions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.TestIamPermissions method.
	A2AHistoryService_TestIamPermissions_FullMethodDescription = "Returns permissions that a caller has on the specified resource."
	// A2AHistoryService_BatchTestIamPermissions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.BatchTestIamPermissions method.
	A2AHistoryService_BatchTestIamPermissions_FullMethodDescription = "Returns permissions that a caller has on the specified resources."
	// A2AHistoryService_AddIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.AddIamBindings method.
	A2AHistoryService_AddIamBindings_FullMethodDescription = "Adds principals or updates the roles existing principals have on an IAM Policy protected resource."
	// A2AHistoryService_RemoveIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.RemoveIamBindings method.
	A2AHistoryService_RemoveIamBindings_FullMethodDescription = "Removes principals or some of the roles they have on an IAM Policy protected resource."
	// A2AHistoryService_ListA2AHistories_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.ListA2AHistories method.
	A2AHistoryService_ListA2AHistories_FullMethodDescription = "Lists all histories."
	// A2AHistoryService_GetA2AHistory_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.GetA2AHistory method.
	A2AHistoryService_GetA2AHistory_FullMethodDescription = "Gets an A2AHistory by its resource name."
	// A2AHistoryService_DeleteA2AHistory_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.DeleteA2AHistory method.
	A2AHistoryService_DeleteA2AHistory_FullMethodDescription = "Deletes an A2AHistory."
	// A2AHistoryService_AppendEvent_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.AppendEvent method.
	A2AHistoryService_AppendEvent_FullMethodDescription = "Appends an event to a given A2AHistory"
	// A2AHistoryService_ListEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.ListEvents method.
	A2AHistoryService_ListEvents_FullMethodDescription = "Lists all events."
	// A2AHistoryService_StreamEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.A2AHistoryService.StreamEvents method.
	A2AHistoryService_StreamEvents_FullMethodDescription = "Stream events."
)
