// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/a2a/extension/history/v1/history.proto

package v1

import (
	v1 "go.alis.build/a2a/lf/a2a/v1"
	v11 "google.golang.org/genproto/googleapis/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v12 "open.alis.services/protobuf/alis/open/iam/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An A2AHistory resource
type A2AHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the A2AHistory.
	// a2ahistories/{context_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Generated display name from the first event in a A2AHistory.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The agent display name, e.g. Finance Agent
	AgentDisplayName string `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	// When this A2AHistory was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2AHistory) Reset() {
	*x = A2AHistory{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AHistory) ProtoMessage() {}

func (x *A2AHistory) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AHistory.ProtoReflect.Descriptor instead.
func (*A2AHistory) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *A2AHistory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *A2AHistory) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *A2AHistory) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *A2AHistory) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

func (x *A2AHistory) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// An A2AHistoryEvent resource
type A2AHistoryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event.
	// a2ahistories/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*A2AHistoryEvent_Task
	//	*A2AHistoryEvent_Message
	//	*A2AHistoryEvent_StatusUpdate
	//	*A2AHistoryEvent_ArtifactUpdate
	Payload isA2AHistoryEvent_Payload `protobuf_oneof:"payload"`
	// When this event was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2AHistoryEvent) Reset() {
	*x = A2AHistoryEvent{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AHistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AHistoryEvent) ProtoMessage() {}

func (x *A2AHistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AHistoryEvent.ProtoReflect.Descriptor instead.
func (*A2AHistoryEvent) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *A2AHistoryEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *A2AHistoryEvent) GetPayload() isA2AHistoryEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *A2AHistoryEvent) GetTask() *v1.Task {
	if x != nil {
		if x, ok := x.Payload.(*A2AHistoryEvent_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *A2AHistoryEvent) GetMessage() *v1.Message {
	if x != nil {
		if x, ok := x.Payload.(*A2AHistoryEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *A2AHistoryEvent) GetStatusUpdate() *v1.TaskStatusUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*A2AHistoryEvent_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *A2AHistoryEvent) GetArtifactUpdate() *v1.TaskArtifactUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*A2AHistoryEvent_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

func (x *A2AHistoryEvent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type isA2AHistoryEvent_Payload interface {
	isA2AHistoryEvent_Payload()
}

type A2AHistoryEvent_Task struct {
	// A Task object containing the current state of the task.
	Task *v1.Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type A2AHistoryEvent_Message struct {
	// A Message object containing a message from the client/user.
	Message *v1.Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type A2AHistoryEvent_StatusUpdate struct {
	// An event indicating a task status update.
	StatusUpdate *v1.TaskStatusUpdateEvent `protobuf:"bytes,4,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type A2AHistoryEvent_ArtifactUpdate struct {
	// An event indicating a task artifact update.
	ArtifactUpdate *v1.TaskArtifactUpdateEvent `protobuf:"bytes,5,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"`
}

func (*A2AHistoryEvent_Task) isA2AHistoryEvent_Payload() {}

func (*A2AHistoryEvent_Message) isA2AHistoryEvent_Payload() {}

func (*A2AHistoryEvent_StatusUpdate) isA2AHistoryEvent_Payload() {}

func (*A2AHistoryEvent_ArtifactUpdate) isA2AHistoryEvent_Payload() {}

// Request to get an A2AHistory.
type GetA2AHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the A2AHistory to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetA2AHistoryRequest) Reset() {
	*x = GetA2AHistoryRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA2AHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA2AHistoryRequest) ProtoMessage() {}

func (x *GetA2AHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA2AHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetA2AHistoryRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetA2AHistoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetA2AHistoryRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to delete an A2AHistory.
type DeleteA2AHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the A2AHistory to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteA2AHistoryRequest) Reset() {
	*x = DeleteA2AHistoryRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteA2AHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteA2AHistoryRequest) ProtoMessage() {}

func (x *DeleteA2AHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteA2AHistoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteA2AHistoryRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteA2AHistoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to list A2AHistories.
type ListA2AHistoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of A2A Histories to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filtering of Histories by the "agent_id" who produced the underlying Events.
	// Example: my-agent-v1. However, this can be any unique identifier that client decides to use.
	AgentId string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListA2AHistoriesRequest) Reset() {
	*x = ListA2AHistoriesRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListA2AHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListA2AHistoriesRequest) ProtoMessage() {}

func (x *ListA2AHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListA2AHistoriesRequest.ProtoReflect.Descriptor instead.
func (*ListA2AHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *ListA2AHistoriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListA2AHistoriesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListA2AHistoriesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListA2AHistoriesRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListA2AHistories.
type ListA2AHistoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of a2a histories.
	Histories []*A2AHistory `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListA2AHistoriesResponse) Reset() {
	*x = ListA2AHistoriesResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListA2AHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListA2AHistoriesResponse) ProtoMessage() {}

func (x *ListA2AHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListA2AHistoriesResponse.ProtoReflect.Descriptor instead.
func (*ListA2AHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *ListA2AHistoriesResponse) GetHistories() []*A2AHistory {
	if x != nil {
		return x.Histories
	}
	return nil
}

func (x *ListA2AHistoriesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to get an event.
type GetA2AHistoryEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event to retrieve.
	// Format: a2ahistories/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetA2AHistoryEventRequest) Reset() {
	*x = GetA2AHistoryEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA2AHistoryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA2AHistoryEventRequest) ProtoMessage() {}

func (x *GetA2AHistoryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA2AHistoryEventRequest.ProtoReflect.Descriptor instead.
func (*GetA2AHistoryEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetA2AHistoryEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetA2AHistoryEventRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to list events.
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent A2AHistory resource name.
	// Format: a2ahistories/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of events to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListA2AHistoryEvents.
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of events.
	Events []*A2AHistoryEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *ListEventsResponse) GetEvents() []*A2AHistoryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to stream events.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent A2AHistory resource name
	// Format: a2ahistories/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to appending an event.
type AppendEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to create.
	// Parent A2AHistory deduced from the event-provided context_id.
	Event *A2AHistoryEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	// Only used on first event in a A2AHistory.
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{10}
}

func (x *AppendEventRequest) GetEvent() *A2AHistoryEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AppendEventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Response to appending an event.
type AppendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventResponse) Reset() {
	*x = AppendEventResponse{}
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventResponse) ProtoMessage() {}

func (x *AppendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventResponse.ProtoReflect.Descriptor instead.
func (*AppendEventResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP(), []int{11}
}

var File_alis_a2a_extension_history_v1_history_proto protoreflect.FileDescriptor

const file_alis_a2a_extension_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"+alis/a2a/extension/history/v1/history.proto\x12\x1dalis.a2a.extension.history.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1aalis/open/iam/v1/iam.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13lf/a2a/v1/a2a.proto\"\xc9\x01\n" +
	"\n" +
	"A2AHistory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayName\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xdc\x02\n" +
	"\x0fA2AHistoryEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04task\x18\x02 \x01(\v2\x0f.lf.a2a.v1.TaskH\x00R\x04task\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x12.lf.a2a.v1.MessageH\x00R\amessage\x12G\n" +
	"\rstatus_update\x18\x04 \x01(\v2 .lf.a2a.v1.TaskStatusUpdateEventH\x00R\fstatusUpdate\x12M\n" +
	"\x0fartifact_update\x18\x05 \x01(\v2\".lf.a2a.v1.TaskArtifactUpdateEventH\x00R\x0eartifactUpdate\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB\t\n" +
	"\apayload\"c\n" +
	"\x14GetA2AHistoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"-\n" +
	"\x17DeleteA2AHistoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaf\x01\n" +
	"\x17ListA2AHistoriesRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"\x8b\x01\n" +
	"\x18ListA2AHistoriesResponse\x12G\n" +
	"\thistories\x18\x01 \x03(\v2).alis.a2a.extension.history.v1.A2AHistoryR\thistories\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"h\n" +
	"\x19GetA2AHistoryEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xa0\x01\n" +
	"\x11ListEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x84\x01\n" +
	"\x12ListEventsResponse\x12F\n" +
	"\x06events\x18\x01 \x03(\v2..alis.a2a.extension.history.v1.A2AHistoryEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"f\n" +
	"\x13StreamEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"{\n" +
	"\x12AppendEventRequest\x12D\n" +
	"\x05event\x18\x02 \x01(\v2..alis.a2a.extension.history.v1.A2AHistoryEventR\x05event\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentIdJ\x04\b\x01\x10\x02\"\x15\n" +
	"\x13AppendEventResponse2\xa4\n" +
	"\n" +
	"\x11A2AHistoryService\x12K\n" +
	"\fGetIamPolicy\x12\".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12K\n" +
	"\fSetIamPolicy\x12\".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12k\n" +
	"\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse\"\x00\x12\x80\x01\n" +
	"\x17BatchTestIamPermissions\x120.alis.open.iam.v1.BatchTestIamPermissionsRequest\x1a1.alis.open.iam.v1.BatchTestIamPermissionsResponse\"\x00\x12R\n" +
	"\x0eAddIamBindings\x12'.alis.open.iam.v1.AddIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12X\n" +
	"\x11RemoveIamBindings\x12*.alis.open.iam.v1.RemoveIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12\x85\x01\n" +
	"\x10ListA2AHistories\x126.alis.a2a.extension.history.v1.ListA2AHistoriesRequest\x1a7.alis.a2a.extension.history.v1.ListA2AHistoriesResponse\"\x00\x12q\n" +
	"\rGetA2AHistory\x123.alis.a2a.extension.history.v1.GetA2AHistoryRequest\x1a).alis.a2a.extension.history.v1.A2AHistory\"\x00\x12w\n" +
	"\x10DeleteA2AHistory\x126.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest\x1a).alis.a2a.extension.history.v1.A2AHistory\"\x00\x12v\n" +
	"\vAppendEvent\x121.alis.a2a.extension.history.v1.AppendEventRequest\x1a2.alis.a2a.extension.history.v1.AppendEventResponse\"\x00\x12s\n" +
	"\n" +
	"ListEvents\x120.alis.a2a.extension.history.v1.ListEventsRequest\x1a1.alis.a2a.extension.history.v1.ListEventsResponse\"\x00\x12v\n" +
	"\fStreamEvents\x122.alis.a2a.extension.history.v1.StreamEventsRequest\x1a..alis.a2a.extension.history.v1.A2AHistoryEvent\"\x000\x01BGZEgithub.com/alis-exchange/a2a-history-go/alis/a2a/extension/history/v1b\x06proto3"

var (
	file_alis_a2a_extension_history_v1_history_proto_rawDescOnce sync.Once
	file_alis_a2a_extension_history_v1_history_proto_rawDescData []byte
)

func file_alis_a2a_extension_history_v1_history_proto_rawDescGZIP() []byte {
	file_alis_a2a_extension_history_v1_history_proto_rawDescOnce.Do(func() {
		file_alis_a2a_extension_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_history_proto_rawDesc), len(file_alis_a2a_extension_history_v1_history_proto_rawDesc)))
	})
	return file_alis_a2a_extension_history_v1_history_proto_rawDescData
}

var file_alis_a2a_extension_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_alis_a2a_extension_history_v1_history_proto_goTypes = []any{
	(*A2AHistory)(nil),                          // 0: alis.a2a.extension.history.v1.A2AHistory
	(*A2AHistoryEvent)(nil),                     // 1: alis.a2a.extension.history.v1.A2AHistoryEvent
	(*GetA2AHistoryRequest)(nil),                // 2: alis.a2a.extension.history.v1.GetA2AHistoryRequest
	(*DeleteA2AHistoryRequest)(nil),             // 3: alis.a2a.extension.history.v1.DeleteA2AHistoryRequest
	(*ListA2AHistoriesRequest)(nil),             // 4: alis.a2a.extension.history.v1.ListA2AHistoriesRequest
	(*ListA2AHistoriesResponse)(nil),            // 5: alis.a2a.extension.history.v1.ListA2AHistoriesResponse
	(*GetA2AHistoryEventRequest)(nil),           // 6: alis.a2a.extension.history.v1.GetA2AHistoryEventRequest
	(*ListEventsRequest)(nil),                   // 7: alis.a2a.extension.history.v1.ListEventsRequest
	(*ListEventsResponse)(nil),                  // 8: alis.a2a.extension.history.v1.ListEventsResponse
	(*StreamEventsRequest)(nil),                 // 9: alis.a2a.extension.history.v1.StreamEventsRequest
	(*AppendEventRequest)(nil),                  // 10: alis.a2a.extension.history.v1.AppendEventRequest
	(*AppendEventResponse)(nil),                 // 11: alis.a2a.extension.history.v1.AppendEventResponse
	(*timestamppb.Timestamp)(nil),               // 12: google.protobuf.Timestamp
	(*v1.Task)(nil),                             // 13: lf.a2a.v1.Task
	(*v1.Message)(nil),                          // 14: lf.a2a.v1.Message
	(*v1.TaskStatusUpdateEvent)(nil),            // 15: lf.a2a.v1.TaskStatusUpdateEvent
	(*v1.TaskArtifactUpdateEvent)(nil),          // 16: lf.a2a.v1.TaskArtifactUpdateEvent
	(*fieldmaskpb.FieldMask)(nil),               // 17: google.protobuf.FieldMask
	(*v11.GetIamPolicyRequest)(nil),             // 18: google.iam.v1.GetIamPolicyRequest
	(*v11.SetIamPolicyRequest)(nil),             // 19: google.iam.v1.SetIamPolicyRequest
	(*v11.TestIamPermissionsRequest)(nil),       // 20: google.iam.v1.TestIamPermissionsRequest
	(*v12.BatchTestIamPermissionsRequest)(nil),  // 21: alis.open.iam.v1.BatchTestIamPermissionsRequest
	(*v12.AddIamBindingsRequest)(nil),           // 22: alis.open.iam.v1.AddIamBindingsRequest
	(*v12.RemoveIamBindingsRequest)(nil),        // 23: alis.open.iam.v1.RemoveIamBindingsRequest
	(*v11.Policy)(nil),                          // 24: google.iam.v1.Policy
	(*v11.TestIamPermissionsResponse)(nil),      // 25: google.iam.v1.TestIamPermissionsResponse
	(*v12.BatchTestIamPermissionsResponse)(nil), // 26: alis.open.iam.v1.BatchTestIamPermissionsResponse
}
var file_alis_a2a_extension_history_v1_history_proto_depIdxs = []int32{
	12, // 0: alis.a2a.extension.history.v1.A2AHistory.create_time:type_name -> google.protobuf.Timestamp
	13, // 1: alis.a2a.extension.history.v1.A2AHistoryEvent.task:type_name -> lf.a2a.v1.Task
	14, // 2: alis.a2a.extension.history.v1.A2AHistoryEvent.message:type_name -> lf.a2a.v1.Message
	15, // 3: alis.a2a.extension.history.v1.A2AHistoryEvent.status_update:type_name -> lf.a2a.v1.TaskStatusUpdateEvent
	16, // 4: alis.a2a.extension.history.v1.A2AHistoryEvent.artifact_update:type_name -> lf.a2a.v1.TaskArtifactUpdateEvent
	12, // 5: alis.a2a.extension.history.v1.A2AHistoryEvent.create_time:type_name -> google.protobuf.Timestamp
	17, // 6: alis.a2a.extension.history.v1.GetA2AHistoryRequest.read_mask:type_name -> google.protobuf.FieldMask
	17, // 7: alis.a2a.extension.history.v1.ListA2AHistoriesRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: alis.a2a.extension.history.v1.ListA2AHistoriesResponse.histories:type_name -> alis.a2a.extension.history.v1.A2AHistory
	17, // 9: alis.a2a.extension.history.v1.GetA2AHistoryEventRequest.read_mask:type_name -> google.protobuf.FieldMask
	17, // 10: alis.a2a.extension.history.v1.ListEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 11: alis.a2a.extension.history.v1.ListEventsResponse.events:type_name -> alis.a2a.extension.history.v1.A2AHistoryEvent
	17, // 12: alis.a2a.extension.history.v1.StreamEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 13: alis.a2a.extension.history.v1.AppendEventRequest.event:type_name -> alis.a2a.extension.history.v1.A2AHistoryEvent
	18, // 14: alis.a2a.extension.history.v1.A2AHistoryService.GetIamPolicy:input_type -> google.iam.v1.GetIamPolicyRequest
	19, // 15: alis.a2a.extension.history.v1.A2AHistoryService.SetIamPolicy:input_type -> google.iam.v1.SetIamPolicyRequest
	20, // 16: alis.a2a.extension.history.v1.A2AHistoryService.TestIamPermissions:input_type -> google.iam.v1.TestIamPermissionsRequest
	21, // 17: alis.a2a.extension.history.v1.A2AHistoryService.BatchTestIamPermissions:input_type -> alis.open.iam.v1.BatchTestIamPermissionsRequest
	22, // 18: alis.a2a.extension.history.v1.A2AHistoryService.AddIamBindings:input_type -> alis.open.iam.v1.AddIamBindingsRequest
	23, // 19: alis.a2a.extension.history.v1.A2AHistoryService.RemoveIamBindings:input_type -> alis.open.iam.v1.RemoveIamBindingsRequest
	4,  // 20: alis.a2a.extension.history.v1.A2AHistoryService.ListA2AHistories:input_type -> alis.a2a.extension.history.v1.ListA2AHistoriesRequest
	2,  // 21: alis.a2a.extension.history.v1.A2AHistoryService.GetA2AHistory:input_type -> alis.a2a.extension.history.v1.GetA2AHistoryRequest
	3,  // 22: alis.a2a.extension.history.v1.A2AHistoryService.DeleteA2AHistory:input_type -> alis.a2a.extension.history.v1.DeleteA2AHistoryRequest
	10, // 23: alis.a2a.extension.history.v1.A2AHistoryService.AppendEvent:input_type -> alis.a2a.extension.history.v1.AppendEventRequest
	7,  // 24: alis.a2a.extension.history.v1.A2AHistoryService.ListEvents:input_type -> alis.a2a.extension.history.v1.ListEventsRequest
	9,  // 25: alis.a2a.extension.history.v1.A2AHistoryService.StreamEvents:input_type -> alis.a2a.extension.history.v1.StreamEventsRequest
	24, // 26: alis.a2a.extension.history.v1.A2AHistoryService.GetIamPolicy:output_type -> google.iam.v1.Policy
	24, // 27: alis.a2a.extension.history.v1.A2AHistoryService.SetIamPolicy:output_type -> google.iam.v1.Policy
	25, // 28: alis.a2a.extension.history.v1.A2AHistoryService.TestIamPermissions:output_type -> google.iam.v1.TestIamPermissionsResponse
	26, // 29: alis.a2a.extension.history.v1.A2AHistoryService.BatchTestIamPermissions:output_type -> alis.open.iam.v1.BatchTestIamPermissionsResponse
	24, // 30: alis.a2a.extension.history.v1.A2AHistoryService.AddIamBindings:output_type -> google.iam.v1.Policy
	24, // 31: alis.a2a.extension.history.v1.A2AHistoryService.RemoveIamBindings:output_type -> google.iam.v1.Policy
	5,  // 32: alis.a2a.extension.history.v1.A2AHistoryService.ListA2AHistories:output_type -> alis.a2a.extension.history.v1.ListA2AHistoriesResponse
	0,  // 33: alis.a2a.extension.history.v1.A2AHistoryService.GetA2AHistory:output_type -> alis.a2a.extension.history.v1.A2AHistory
	0,  // 34: alis.a2a.extension.history.v1.A2AHistoryService.DeleteA2AHistory:output_type -> alis.a2a.extension.history.v1.A2AHistory
	11, // 35: alis.a2a.extension.history.v1.A2AHistoryService.AppendEvent:output_type -> alis.a2a.extension.history.v1.AppendEventResponse
	8,  // 36: alis.a2a.extension.history.v1.A2AHistoryService.ListEvents:output_type -> alis.a2a.extension.history.v1.ListEventsResponse
	1,  // 37: alis.a2a.extension.history.v1.A2AHistoryService.StreamEvents:output_type -> alis.a2a.extension.history.v1.A2AHistoryEvent
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_alis_a2a_extension_history_v1_history_proto_init() }
func file_alis_a2a_extension_history_v1_history_proto_init() {
	if File_alis_a2a_extension_history_v1_history_proto != nil {
		return
	}
	file_alis_a2a_extension_history_v1_history_proto_msgTypes[1].OneofWrappers = []any{
		(*A2AHistoryEvent_Task)(nil),
		(*A2AHistoryEvent_Message)(nil),
		(*A2AHistoryEvent_StatusUpdate)(nil),
		(*A2AHistoryEvent_ArtifactUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_history_proto_rawDesc), len(file_alis_a2a_extension_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_a2a_extension_history_v1_history_proto_goTypes,
		DependencyIndexes: file_alis_a2a_extension_history_v1_history_proto_depIdxs,
		MessageInfos:      file_alis_a2a_extension_history_v1_history_proto_msgTypes,
	}.Build()
	File_alis_a2a_extension_history_v1_history_proto = out.File
	file_alis_a2a_extension_history_v1_history_proto_goTypes = nil
	file_alis_a2a_extension_history_v1_history_proto_depIdxs = nil
}
