// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: alis/a2a/extension/history/v1/history.proto

package v1

import (
	context "context"
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v11 "open.alis.services/protobuf/alis/open/iam/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	A2AHistoryService_GetIamPolicy_FullMethodName            = "/alis.a2a.extension.history.v1.A2AHistoryService/GetIamPolicy"
	A2AHistoryService_SetIamPolicy_FullMethodName            = "/alis.a2a.extension.history.v1.A2AHistoryService/SetIamPolicy"
	A2AHistoryService_TestIamPermissions_FullMethodName      = "/alis.a2a.extension.history.v1.A2AHistoryService/TestIamPermissions"
	A2AHistoryService_BatchTestIamPermissions_FullMethodName = "/alis.a2a.extension.history.v1.A2AHistoryService/BatchTestIamPermissions"
	A2AHistoryService_AddIamBindings_FullMethodName          = "/alis.a2a.extension.history.v1.A2AHistoryService/AddIamBindings"
	A2AHistoryService_RemoveIamBindings_FullMethodName       = "/alis.a2a.extension.history.v1.A2AHistoryService/RemoveIamBindings"
	A2AHistoryService_ListA2AHistories_FullMethodName        = "/alis.a2a.extension.history.v1.A2AHistoryService/ListA2AHistories"
	A2AHistoryService_GetA2AHistory_FullMethodName           = "/alis.a2a.extension.history.v1.A2AHistoryService/GetA2AHistory"
	A2AHistoryService_DeleteA2AHistory_FullMethodName        = "/alis.a2a.extension.history.v1.A2AHistoryService/DeleteA2AHistory"
	A2AHistoryService_AppendEvent_FullMethodName             = "/alis.a2a.extension.history.v1.A2AHistoryService/AppendEvent"
	A2AHistoryService_ListEvents_FullMethodName              = "/alis.a2a.extension.history.v1.A2AHistoryService/ListEvents"
	A2AHistoryService_StreamEvents_FullMethodName            = "/alis.a2a.extension.history.v1.A2AHistoryService/StreamEvents"
)

// A2AHistoryServiceClient is the client API for A2AHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A2AHistoryService
type A2AHistoryServiceClient interface {
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error)
	// Returns permissions that a caller has on the specified resources.
	BatchTestIamPermissions(ctx context.Context, in *v11.BatchTestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.BatchTestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(ctx context.Context, in *v11.AddIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(ctx context.Context, in *v11.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Lists all histories.
	ListA2AHistories(ctx context.Context, in *ListA2AHistoriesRequest, opts ...grpc.CallOption) (*ListA2AHistoriesResponse, error)
	// Gets an A2AHistory by its resource name.
	GetA2AHistory(ctx context.Context, in *GetA2AHistoryRequest, opts ...grpc.CallOption) (*A2AHistory, error)
	// Deletes an A2AHistory.
	DeleteA2AHistory(ctx context.Context, in *DeleteA2AHistoryRequest, opts ...grpc.CallOption) (*A2AHistory, error)
	// Appends an event to a given A2AHistory
	AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error)
	// Lists all events.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Stream events.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[A2AHistoryEvent], error)
}

type a2AHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewA2AHistoryServiceClient(cc grpc.ClientConnInterface) A2AHistoryServiceClient {
	return &a2AHistoryServiceClient{cc}
}

func (c *a2AHistoryServiceClient) GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, A2AHistoryService_GetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, A2AHistoryService_SetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, A2AHistoryService_TestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) BatchTestIamPermissions(ctx context.Context, in *v11.BatchTestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.BatchTestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.BatchTestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, A2AHistoryService_BatchTestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) AddIamBindings(ctx context.Context, in *v11.AddIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, A2AHistoryService_AddIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) RemoveIamBindings(ctx context.Context, in *v11.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, A2AHistoryService_RemoveIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) ListA2AHistories(ctx context.Context, in *ListA2AHistoriesRequest, opts ...grpc.CallOption) (*ListA2AHistoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListA2AHistoriesResponse)
	err := c.cc.Invoke(ctx, A2AHistoryService_ListA2AHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) GetA2AHistory(ctx context.Context, in *GetA2AHistoryRequest, opts ...grpc.CallOption) (*A2AHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(A2AHistory)
	err := c.cc.Invoke(ctx, A2AHistoryService_GetA2AHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) DeleteA2AHistory(ctx context.Context, in *DeleteA2AHistoryRequest, opts ...grpc.CallOption) (*A2AHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(A2AHistory)
	err := c.cc.Invoke(ctx, A2AHistoryService_DeleteA2AHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEventResponse)
	err := c.cc.Invoke(ctx, A2AHistoryService_AppendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, A2AHistoryService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AHistoryServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[A2AHistoryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &A2AHistoryService_ServiceDesc.Streams[0], A2AHistoryService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, A2AHistoryEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AHistoryService_StreamEventsClient = grpc.ServerStreamingClient[A2AHistoryEvent]

// A2AHistoryServiceServer is the server API for A2AHistoryService service.
// All implementations must embed UnimplementedA2AHistoryServiceServer
// for forward compatibility.
//
// A2AHistoryService
type A2AHistoryServiceServer interface {
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(context.Context, *v1.GetIamPolicyRequest) (*v1.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(context.Context, *v1.SetIamPolicyRequest) (*v1.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(context.Context, *v1.TestIamPermissionsRequest) (*v1.TestIamPermissionsResponse, error)
	// Returns permissions that a caller has on the specified resources.
	BatchTestIamPermissions(context.Context, *v11.BatchTestIamPermissionsRequest) (*v11.BatchTestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(context.Context, *v11.AddIamBindingsRequest) (*v1.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(context.Context, *v11.RemoveIamBindingsRequest) (*v1.Policy, error)
	// Lists all histories.
	ListA2AHistories(context.Context, *ListA2AHistoriesRequest) (*ListA2AHistoriesResponse, error)
	// Gets an A2AHistory by its resource name.
	GetA2AHistory(context.Context, *GetA2AHistoryRequest) (*A2AHistory, error)
	// Deletes an A2AHistory.
	DeleteA2AHistory(context.Context, *DeleteA2AHistoryRequest) (*A2AHistory, error)
	// Appends an event to a given A2AHistory
	AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error)
	// Lists all events.
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Stream events.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[A2AHistoryEvent]) error
	mustEmbedUnimplementedA2AHistoryServiceServer()
}

// UnimplementedA2AHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedA2AHistoryServiceServer struct{}

func (UnimplementedA2AHistoryServiceServer) GetIamPolicy(context.Context, *v1.GetIamPolicyRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedA2AHistoryServiceServer) SetIamPolicy(context.Context, *v1.SetIamPolicyRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedA2AHistoryServiceServer) TestIamPermissions(context.Context, *v1.TestIamPermissionsRequest) (*v1.TestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestIamPermissions not implemented")
}
func (UnimplementedA2AHistoryServiceServer) BatchTestIamPermissions(context.Context, *v11.BatchTestIamPermissionsRequest) (*v11.BatchTestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchTestIamPermissions not implemented")
}
func (UnimplementedA2AHistoryServiceServer) AddIamBindings(context.Context, *v11.AddIamBindingsRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIamBindings not implemented")
}
func (UnimplementedA2AHistoryServiceServer) RemoveIamBindings(context.Context, *v11.RemoveIamBindingsRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIamBindings not implemented")
}
func (UnimplementedA2AHistoryServiceServer) ListA2AHistories(context.Context, *ListA2AHistoriesRequest) (*ListA2AHistoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListA2AHistories not implemented")
}
func (UnimplementedA2AHistoryServiceServer) GetA2AHistory(context.Context, *GetA2AHistoryRequest) (*A2AHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetA2AHistory not implemented")
}
func (UnimplementedA2AHistoryServiceServer) DeleteA2AHistory(context.Context, *DeleteA2AHistoryRequest) (*A2AHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteA2AHistory not implemented")
}
func (UnimplementedA2AHistoryServiceServer) AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedA2AHistoryServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedA2AHistoryServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[A2AHistoryEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedA2AHistoryServiceServer) mustEmbedUnimplementedA2AHistoryServiceServer() {}
func (UnimplementedA2AHistoryServiceServer) testEmbeddedByValue()                           {}

// UnsafeA2AHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to A2AHistoryServiceServer will
// result in compilation errors.
type UnsafeA2AHistoryServiceServer interface {
	mustEmbedUnimplementedA2AHistoryServiceServer()
}

func RegisterA2AHistoryServiceServer(s grpc.ServiceRegistrar, srv A2AHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedA2AHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&A2AHistoryService_ServiceDesc, srv)
}

func _A2AHistoryService_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).GetIamPolicy(ctx, req.(*v1.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).SetIamPolicy(ctx, req.(*v1.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).TestIamPermissions(ctx, req.(*v1.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_BatchTestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.BatchTestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).BatchTestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_BatchTestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).BatchTestIamPermissions(ctx, req.(*v11.BatchTestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_AddIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.AddIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).AddIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_AddIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).AddIamBindings(ctx, req.(*v11.AddIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_RemoveIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.RemoveIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).RemoveIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_RemoveIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).RemoveIamBindings(ctx, req.(*v11.RemoveIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_ListA2AHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListA2AHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).ListA2AHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_ListA2AHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).ListA2AHistories(ctx, req.(*ListA2AHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_GetA2AHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetA2AHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).GetA2AHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_GetA2AHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).GetA2AHistory(ctx, req.(*GetA2AHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_DeleteA2AHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteA2AHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).DeleteA2AHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_DeleteA2AHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).DeleteA2AHistory(ctx, req.(*DeleteA2AHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).AppendEvent(ctx, req.(*AppendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AHistoryServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AHistoryService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AHistoryServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AHistoryService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(A2AHistoryServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, A2AHistoryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AHistoryService_StreamEventsServer = grpc.ServerStreamingServer[A2AHistoryEvent]

// A2AHistoryService_ServiceDesc is the grpc.ServiceDesc for A2AHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A2AHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.a2a.extension.history.v1.A2AHistoryService",
	HandlerType: (*A2AHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIamPolicy",
			Handler:    _A2AHistoryService_GetIamPolicy_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _A2AHistoryService_SetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _A2AHistoryService_TestIamPermissions_Handler,
		},
		{
			MethodName: "BatchTestIamPermissions",
			Handler:    _A2AHistoryService_BatchTestIamPermissions_Handler,
		},
		{
			MethodName: "AddIamBindings",
			Handler:    _A2AHistoryService_AddIamBindings_Handler,
		},
		{
			MethodName: "RemoveIamBindings",
			Handler:    _A2AHistoryService_RemoveIamBindings_Handler,
		},
		{
			MethodName: "ListA2AHistories",
			Handler:    _A2AHistoryService_ListA2AHistories_Handler,
		},
		{
			MethodName: "GetA2AHistory",
			Handler:    _A2AHistoryService_GetA2AHistory_Handler,
		},
		{
			MethodName: "DeleteA2AHistory",
			Handler:    _A2AHistoryService_DeleteA2AHistory_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _A2AHistoryService_AppendEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _A2AHistoryService_ListEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _A2AHistoryService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "alis/a2a/extension/history/v1/history.proto",
}
