// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/a2a/extension/history/v1/session.proto

package v1

import (
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v11 "open.alis.services/protobuf/alis/open/iam/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An Session resource
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the session.
	// sessions/{context_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Generated display name from the first event in a session.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The agent display name, e.g. Finance Agent
	AgentDisplayName string `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	// When this session was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Session) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

func (x *Session) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/*
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Optional app acting on behalf of the user.
	// Format: apps/*
	App           string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Client) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

// An Event resource
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event.
	// sessions/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The client, if any, that created the event.
	// If empty, the event was created by the agent.
	Client *Client `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Task
	//	*Event_Message
	//	*Event_StatusUpdate
	//	*Event_ArtifactUpdate
	Payload isEvent_Payload `protobuf_oneof:"payload"`
	// When this event was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTask() *Task {
	if x != nil {
		if x, ok := x.Payload.(*Event_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Event_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Event) GetStatusUpdate() *TaskStatusUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *Event) GetArtifactUpdate() *TaskArtifactUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

func (x *Event) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Task struct {
	// A Task object containing the current state of the task.
	Task *Task `protobuf:"bytes,3,opt,name=task,proto3,oneof"`
}

type Event_Message struct {
	// A Message object containing a message from the client/user.
	Message *Message `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type Event_StatusUpdate struct {
	// An event indicating a task status update.
	StatusUpdate *TaskStatusUpdateEvent `protobuf:"bytes,5,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type Event_ArtifactUpdate struct {
	// An event indicating a task artifact update.
	ArtifactUpdate *TaskArtifactUpdateEvent `protobuf:"bytes,6,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"`
}

func (*Event_Task) isEvent_Payload() {}

func (*Event_Message) isEvent_Payload() {}

func (*Event_StatusUpdate) isEvent_Payload() {}

func (*Event_ArtifactUpdate) isEvent_Payload() {}

// Request to get an session.
type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the session to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSessionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to delete an session.
type DeleteSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the session to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to list sessions.
type ListSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of sessions to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSessionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListSessions.
type ListSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of sessions.
	Sessions []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to get a batch of sessions by their resource names.
type BatchGetSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource names of the sessions to retrieve.
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSessionsRequest) Reset() {
	*x = BatchGetSessionsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSessionsRequest) ProtoMessage() {}

func (x *BatchGetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSessionsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetSessionsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *BatchGetSessionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for BatchGetSessions.
type BatchGetSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved sessions.
	Sessions      []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSessionsResponse) Reset() {
	*x = BatchGetSessionsResponse{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSessionsResponse) ProtoMessage() {}

func (x *BatchGetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSessionsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Request to batch delete sessions.
type BatchDeleteSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource names of the sessions to delete.
	// Format: sessions/{context_id}
	Names         []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteSessionsRequest) Reset() {
	*x = BatchDeleteSessionsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteSessionsRequest) ProtoMessage() {}

func (x *BatchDeleteSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteSessionsRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteSessionsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeleteSessionsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// Response for BatchDeleteSessions.
type BatchDeleteSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deleted sessions.
	Sessions      []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteSessionsResponse) Reset() {
	*x = BatchDeleteSessionsResponse{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteSessionsResponse) ProtoMessage() {}

func (x *BatchDeleteSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteSessionsResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteSessionsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *BatchDeleteSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Request to stream sessions.
type StreamSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSessionsRequest) Reset() {
	*x = StreamSessionsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSessionsRequest) ProtoMessage() {}

func (x *StreamSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSessionsRequest.ProtoReflect.Descriptor instead.
func (*StreamSessionsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *StreamSessionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to create an event.
type CreateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to create.
	// Parent session deduced from context_id.
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	// Only used on first event in a session.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The agent display name, e.g. Finance Agent
	// Only used on first event in a session.
	AgentDisplayName string `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CreateEventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateEventRequest) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

// Request to get an event.
type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the event to retrieve.
	// Format: sessions/{context_id}/events/{event_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to list events.
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent session resource name.
	// Format: sessions/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of events to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *ListEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response for ListEvents.
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of events.
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// A token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to batch create events.
type BatchCreateEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of events to create.
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// The agent_id, e.g. finance-agent-v1
	// Only used on first event in a session.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The agent display name, e.g. Finance Agent
	// Only used on first event in a session.
	AgentDisplayName string `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchCreateEventsRequest) Reset() {
	*x = BatchCreateEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsRequest) ProtoMessage() {}

func (x *BatchCreateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreateEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *BatchCreateEventsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BatchCreateEventsRequest) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

// Response for BatchCreateEvents.
type BatchCreateEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created events.
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateEventsResponse) Reset() {
	*x = BatchCreateEventsResponse{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsResponse) ProtoMessage() {}

func (x *BatchCreateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsResponse) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{17}
}

func (x *BatchCreateEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Request to stream events.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent session resource name
	// Format: sessions/{context_id}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// A read mask to specify which fields to return.
	// If not specified, view will determine the fields returned.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{18}
}

func (x *StreamEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamEventsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type SetSessionDisplayNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the session to update.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The new display name.
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionDisplayNameRequest) Reset() {
	*x = SetSessionDisplayNameRequest{}
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionDisplayNameRequest) ProtoMessage() {}

func (x *SetSessionDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_a2a_extension_history_v1_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*SetSessionDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP(), []int{19}
}

func (x *SetSessionDisplayNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSessionDisplayNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_alis_a2a_extension_history_v1_session_proto protoreflect.FileDescriptor

const file_alis_a2a_extension_history_v1_session_proto_rawDesc = "" +
	"\n" +
	"+alis/a2a/extension/history/v1/session.proto\x12\x1dalis.a2a.extension.history.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1aalis/open/iam/v1/iam.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a'alis/a2a/extension/history/v1/a2a.proto\"\xc6\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayName\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\".\n" +
	"\x06Client\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\"\xe1\x03\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06client\x18\x02 \x01(\v2%.alis.a2a.extension.history.v1.ClientR\x06client\x129\n" +
	"\x04task\x18\x03 \x01(\v2#.alis.a2a.extension.history.v1.TaskH\x00R\x04task\x12B\n" +
	"\amessage\x18\x04 \x01(\v2&.alis.a2a.extension.history.v1.MessageH\x00R\amessage\x12[\n" +
	"\rstatus_update\x18\x05 \x01(\v24.alis.a2a.extension.history.v1.TaskStatusUpdateEventH\x00R\fstatusUpdate\x12a\n" +
	"\x0fartifact_update\x18\x06 \x01(\v26.alis.a2a.extension.history.v1.TaskArtifactUpdateEventH\x00R\x0eartifactUpdate\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB\t\n" +
	"\apayload\"`\n" +
	"\x11GetSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"*\n" +
	"\x14DeleteSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x90\x01\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"\x82\x01\n" +
	"\x14ListSessionsResponse\x12B\n" +
	"\bsessions\x18\x01 \x03(\v2&.alis.a2a.extension.history.v1.SessionR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"n\n" +
	"\x17BatchGetSessionsRequest\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x127\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"^\n" +
	"\x18BatchGetSessionsResponse\x12B\n" +
	"\bsessions\x18\x01 \x03(\v2&.alis.a2a.extension.history.v1.SessionR\bsessions\"8\n" +
	"\x1aBatchDeleteSessionsRequest\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05namesJ\x04\b\x01\x10\x02\"a\n" +
	"\x1bBatchDeleteSessionsResponse\x12B\n" +
	"\bsessions\x18\x01 \x03(\v2&.alis.a2a.extension.history.v1.SessionR\bsessions\"V\n" +
	"\x15StreamSessionsRequest\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"\x9f\x01\n" +
	"\x12CreateEventRequest\x12:\n" +
	"\x05event\x18\x02 \x01(\v2$.alis.a2a.extension.history.v1.EventR\x05event\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayNameJ\x04\b\x01\x10\x02\"^\n" +
	"\x0fGetEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xa0\x01\n" +
	"\x11ListEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"z\n" +
	"\x12ListEventsResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.alis.a2a.extension.history.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa1\x01\n" +
	"\x18BatchCreateEventsRequest\x12<\n" +
	"\x06events\x18\x02 \x03(\v2$.alis.a2a.extension.history.v1.EventR\x06events\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayName\"Y\n" +
	"\x19BatchCreateEventsResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.alis.a2a.extension.history.v1.EventR\x06events\"f\n" +
	"\x13StreamEventsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"U\n" +
	"\x1cSetSessionDisplayNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName2\xf3\x0e\n" +
	"\x0fSessionsService\x12K\n" +
	"\fGetIamPolicy\x12\".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12K\n" +
	"\fSetIamPolicy\x12\".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12k\n" +
	"\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse\"\x00\x12\x80\x01\n" +
	"\x17BatchTestIamPermissions\x120.alis.open.iam.v1.BatchTestIamPermissionsRequest\x1a1.alis.open.iam.v1.BatchTestIamPermissionsResponse\"\x00\x12R\n" +
	"\x0eAddIamBindings\x12'.alis.open.iam.v1.AddIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12X\n" +
	"\x11RemoveIamBindings\x12*.alis.open.iam.v1.RemoveIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12y\n" +
	"\fListSessions\x122.alis.a2a.extension.history.v1.ListSessionsRequest\x1a3.alis.a2a.extension.history.v1.ListSessionsResponse\"\x00\x12h\n" +
	"\n" +
	"GetSession\x120.alis.a2a.extension.history.v1.GetSessionRequest\x1a&.alis.a2a.extension.history.v1.Session\"\x00\x12~\n" +
	"\x15SetSessionDisplayName\x12;.alis.a2a.extension.history.v1.SetSessionDisplayNameRequest\x1a&.alis.a2a.extension.history.v1.Session\"\x00\x12n\n" +
	"\rDeleteSession\x123.alis.a2a.extension.history.v1.DeleteSessionRequest\x1a&.alis.a2a.extension.history.v1.Session\"\x00\x12\x85\x01\n" +
	"\x10BatchGetSessions\x126.alis.a2a.extension.history.v1.BatchGetSessionsRequest\x1a7.alis.a2a.extension.history.v1.BatchGetSessionsResponse\"\x00\x12\x8e\x01\n" +
	"\x13BatchDeleteSessions\x129.alis.a2a.extension.history.v1.BatchDeleteSessionsRequest\x1a:.alis.a2a.extension.history.v1.BatchDeleteSessionsResponse\"\x00\x12\x88\x01\n" +
	"\x11BatchCreateEvents\x127.alis.a2a.extension.history.v1.BatchCreateEventsRequest\x1a8.alis.a2a.extension.history.v1.BatchCreateEventsResponse\"\x00\x12h\n" +
	"\vCreateEvent\x121.alis.a2a.extension.history.v1.CreateEventRequest\x1a$.alis.a2a.extension.history.v1.Event\"\x00\x12b\n" +
	"\bGetEvent\x12..alis.a2a.extension.history.v1.GetEventRequest\x1a$.alis.a2a.extension.history.v1.Event\"\x00\x12s\n" +
	"\n" +
	"ListEvents\x120.alis.a2a.extension.history.v1.ListEventsRequest\x1a1.alis.a2a.extension.history.v1.ListEventsResponse\"\x00\x12l\n" +
	"\fStreamEvents\x122.alis.a2a.extension.history.v1.StreamEventsRequest\x1a$.alis.a2a.extension.history.v1.Event\"\x000\x01BGZEgithub.com/alis-exchange/a2a-history-go/alis/a2a/extension/history/v1b\x06proto3"

var (
	file_alis_a2a_extension_history_v1_session_proto_rawDescOnce sync.Once
	file_alis_a2a_extension_history_v1_session_proto_rawDescData []byte
)

func file_alis_a2a_extension_history_v1_session_proto_rawDescGZIP() []byte {
	file_alis_a2a_extension_history_v1_session_proto_rawDescOnce.Do(func() {
		file_alis_a2a_extension_history_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_session_proto_rawDesc), len(file_alis_a2a_extension_history_v1_session_proto_rawDesc)))
	})
	return file_alis_a2a_extension_history_v1_session_proto_rawDescData
}

var file_alis_a2a_extension_history_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_alis_a2a_extension_history_v1_session_proto_goTypes = []any{
	(*Session)(nil),                             // 0: alis.a2a.extension.history.v1.Session
	(*Client)(nil),                              // 1: alis.a2a.extension.history.v1.Client
	(*Event)(nil),                               // 2: alis.a2a.extension.history.v1.Event
	(*GetSessionRequest)(nil),                   // 3: alis.a2a.extension.history.v1.GetSessionRequest
	(*DeleteSessionRequest)(nil),                // 4: alis.a2a.extension.history.v1.DeleteSessionRequest
	(*ListSessionsRequest)(nil),                 // 5: alis.a2a.extension.history.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),                // 6: alis.a2a.extension.history.v1.ListSessionsResponse
	(*BatchGetSessionsRequest)(nil),             // 7: alis.a2a.extension.history.v1.BatchGetSessionsRequest
	(*BatchGetSessionsResponse)(nil),            // 8: alis.a2a.extension.history.v1.BatchGetSessionsResponse
	(*BatchDeleteSessionsRequest)(nil),          // 9: alis.a2a.extension.history.v1.BatchDeleteSessionsRequest
	(*BatchDeleteSessionsResponse)(nil),         // 10: alis.a2a.extension.history.v1.BatchDeleteSessionsResponse
	(*StreamSessionsRequest)(nil),               // 11: alis.a2a.extension.history.v1.StreamSessionsRequest
	(*CreateEventRequest)(nil),                  // 12: alis.a2a.extension.history.v1.CreateEventRequest
	(*GetEventRequest)(nil),                     // 13: alis.a2a.extension.history.v1.GetEventRequest
	(*ListEventsRequest)(nil),                   // 14: alis.a2a.extension.history.v1.ListEventsRequest
	(*ListEventsResponse)(nil),                  // 15: alis.a2a.extension.history.v1.ListEventsResponse
	(*BatchCreateEventsRequest)(nil),            // 16: alis.a2a.extension.history.v1.BatchCreateEventsRequest
	(*BatchCreateEventsResponse)(nil),           // 17: alis.a2a.extension.history.v1.BatchCreateEventsResponse
	(*StreamEventsRequest)(nil),                 // 18: alis.a2a.extension.history.v1.StreamEventsRequest
	(*SetSessionDisplayNameRequest)(nil),        // 19: alis.a2a.extension.history.v1.SetSessionDisplayNameRequest
	(*timestamppb.Timestamp)(nil),               // 20: google.protobuf.Timestamp
	(*Task)(nil),                                // 21: alis.a2a.extension.history.v1.Task
	(*Message)(nil),                             // 22: alis.a2a.extension.history.v1.Message
	(*TaskStatusUpdateEvent)(nil),               // 23: alis.a2a.extension.history.v1.TaskStatusUpdateEvent
	(*TaskArtifactUpdateEvent)(nil),             // 24: alis.a2a.extension.history.v1.TaskArtifactUpdateEvent
	(*fieldmaskpb.FieldMask)(nil),               // 25: google.protobuf.FieldMask
	(*v1.GetIamPolicyRequest)(nil),              // 26: google.iam.v1.GetIamPolicyRequest
	(*v1.SetIamPolicyRequest)(nil),              // 27: google.iam.v1.SetIamPolicyRequest
	(*v1.TestIamPermissionsRequest)(nil),        // 28: google.iam.v1.TestIamPermissionsRequest
	(*v11.BatchTestIamPermissionsRequest)(nil),  // 29: alis.open.iam.v1.BatchTestIamPermissionsRequest
	(*v11.AddIamBindingsRequest)(nil),           // 30: alis.open.iam.v1.AddIamBindingsRequest
	(*v11.RemoveIamBindingsRequest)(nil),        // 31: alis.open.iam.v1.RemoveIamBindingsRequest
	(*v1.Policy)(nil),                           // 32: google.iam.v1.Policy
	(*v1.TestIamPermissionsResponse)(nil),       // 33: google.iam.v1.TestIamPermissionsResponse
	(*v11.BatchTestIamPermissionsResponse)(nil), // 34: alis.open.iam.v1.BatchTestIamPermissionsResponse
}
var file_alis_a2a_extension_history_v1_session_proto_depIdxs = []int32{
	20, // 0: alis.a2a.extension.history.v1.Session.create_time:type_name -> google.protobuf.Timestamp
	1,  // 1: alis.a2a.extension.history.v1.Event.client:type_name -> alis.a2a.extension.history.v1.Client
	21, // 2: alis.a2a.extension.history.v1.Event.task:type_name -> alis.a2a.extension.history.v1.Task
	22, // 3: alis.a2a.extension.history.v1.Event.message:type_name -> alis.a2a.extension.history.v1.Message
	23, // 4: alis.a2a.extension.history.v1.Event.status_update:type_name -> alis.a2a.extension.history.v1.TaskStatusUpdateEvent
	24, // 5: alis.a2a.extension.history.v1.Event.artifact_update:type_name -> alis.a2a.extension.history.v1.TaskArtifactUpdateEvent
	20, // 6: alis.a2a.extension.history.v1.Event.create_time:type_name -> google.protobuf.Timestamp
	25, // 7: alis.a2a.extension.history.v1.GetSessionRequest.read_mask:type_name -> google.protobuf.FieldMask
	25, // 8: alis.a2a.extension.history.v1.ListSessionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 9: alis.a2a.extension.history.v1.ListSessionsResponse.sessions:type_name -> alis.a2a.extension.history.v1.Session
	25, // 10: alis.a2a.extension.history.v1.BatchGetSessionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 11: alis.a2a.extension.history.v1.BatchGetSessionsResponse.sessions:type_name -> alis.a2a.extension.history.v1.Session
	0,  // 12: alis.a2a.extension.history.v1.BatchDeleteSessionsResponse.sessions:type_name -> alis.a2a.extension.history.v1.Session
	25, // 13: alis.a2a.extension.history.v1.StreamSessionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 14: alis.a2a.extension.history.v1.CreateEventRequest.event:type_name -> alis.a2a.extension.history.v1.Event
	25, // 15: alis.a2a.extension.history.v1.GetEventRequest.read_mask:type_name -> google.protobuf.FieldMask
	25, // 16: alis.a2a.extension.history.v1.ListEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 17: alis.a2a.extension.history.v1.ListEventsResponse.events:type_name -> alis.a2a.extension.history.v1.Event
	2,  // 18: alis.a2a.extension.history.v1.BatchCreateEventsRequest.events:type_name -> alis.a2a.extension.history.v1.Event
	2,  // 19: alis.a2a.extension.history.v1.BatchCreateEventsResponse.events:type_name -> alis.a2a.extension.history.v1.Event
	25, // 20: alis.a2a.extension.history.v1.StreamEventsRequest.read_mask:type_name -> google.protobuf.FieldMask
	26, // 21: alis.a2a.extension.history.v1.SessionsService.GetIamPolicy:input_type -> google.iam.v1.GetIamPolicyRequest
	27, // 22: alis.a2a.extension.history.v1.SessionsService.SetIamPolicy:input_type -> google.iam.v1.SetIamPolicyRequest
	28, // 23: alis.a2a.extension.history.v1.SessionsService.TestIamPermissions:input_type -> google.iam.v1.TestIamPermissionsRequest
	29, // 24: alis.a2a.extension.history.v1.SessionsService.BatchTestIamPermissions:input_type -> alis.open.iam.v1.BatchTestIamPermissionsRequest
	30, // 25: alis.a2a.extension.history.v1.SessionsService.AddIamBindings:input_type -> alis.open.iam.v1.AddIamBindingsRequest
	31, // 26: alis.a2a.extension.history.v1.SessionsService.RemoveIamBindings:input_type -> alis.open.iam.v1.RemoveIamBindingsRequest
	5,  // 27: alis.a2a.extension.history.v1.SessionsService.ListSessions:input_type -> alis.a2a.extension.history.v1.ListSessionsRequest
	3,  // 28: alis.a2a.extension.history.v1.SessionsService.GetSession:input_type -> alis.a2a.extension.history.v1.GetSessionRequest
	19, // 29: alis.a2a.extension.history.v1.SessionsService.SetSessionDisplayName:input_type -> alis.a2a.extension.history.v1.SetSessionDisplayNameRequest
	4,  // 30: alis.a2a.extension.history.v1.SessionsService.DeleteSession:input_type -> alis.a2a.extension.history.v1.DeleteSessionRequest
	7,  // 31: alis.a2a.extension.history.v1.SessionsService.BatchGetSessions:input_type -> alis.a2a.extension.history.v1.BatchGetSessionsRequest
	9,  // 32: alis.a2a.extension.history.v1.SessionsService.BatchDeleteSessions:input_type -> alis.a2a.extension.history.v1.BatchDeleteSessionsRequest
	16, // 33: alis.a2a.extension.history.v1.SessionsService.BatchCreateEvents:input_type -> alis.a2a.extension.history.v1.BatchCreateEventsRequest
	12, // 34: alis.a2a.extension.history.v1.SessionsService.CreateEvent:input_type -> alis.a2a.extension.history.v1.CreateEventRequest
	13, // 35: alis.a2a.extension.history.v1.SessionsService.GetEvent:input_type -> alis.a2a.extension.history.v1.GetEventRequest
	14, // 36: alis.a2a.extension.history.v1.SessionsService.ListEvents:input_type -> alis.a2a.extension.history.v1.ListEventsRequest
	18, // 37: alis.a2a.extension.history.v1.SessionsService.StreamEvents:input_type -> alis.a2a.extension.history.v1.StreamEventsRequest
	32, // 38: alis.a2a.extension.history.v1.SessionsService.GetIamPolicy:output_type -> google.iam.v1.Policy
	32, // 39: alis.a2a.extension.history.v1.SessionsService.SetIamPolicy:output_type -> google.iam.v1.Policy
	33, // 40: alis.a2a.extension.history.v1.SessionsService.TestIamPermissions:output_type -> google.iam.v1.TestIamPermissionsResponse
	34, // 41: alis.a2a.extension.history.v1.SessionsService.BatchTestIamPermissions:output_type -> alis.open.iam.v1.BatchTestIamPermissionsResponse
	32, // 42: alis.a2a.extension.history.v1.SessionsService.AddIamBindings:output_type -> google.iam.v1.Policy
	32, // 43: alis.a2a.extension.history.v1.SessionsService.RemoveIamBindings:output_type -> google.iam.v1.Policy
	6,  // 44: alis.a2a.extension.history.v1.SessionsService.ListSessions:output_type -> alis.a2a.extension.history.v1.ListSessionsResponse
	0,  // 45: alis.a2a.extension.history.v1.SessionsService.GetSession:output_type -> alis.a2a.extension.history.v1.Session
	0,  // 46: alis.a2a.extension.history.v1.SessionsService.SetSessionDisplayName:output_type -> alis.a2a.extension.history.v1.Session
	0,  // 47: alis.a2a.extension.history.v1.SessionsService.DeleteSession:output_type -> alis.a2a.extension.history.v1.Session
	8,  // 48: alis.a2a.extension.history.v1.SessionsService.BatchGetSessions:output_type -> alis.a2a.extension.history.v1.BatchGetSessionsResponse
	10, // 49: alis.a2a.extension.history.v1.SessionsService.BatchDeleteSessions:output_type -> alis.a2a.extension.history.v1.BatchDeleteSessionsResponse
	17, // 50: alis.a2a.extension.history.v1.SessionsService.BatchCreateEvents:output_type -> alis.a2a.extension.history.v1.BatchCreateEventsResponse
	2,  // 51: alis.a2a.extension.history.v1.SessionsService.CreateEvent:output_type -> alis.a2a.extension.history.v1.Event
	2,  // 52: alis.a2a.extension.history.v1.SessionsService.GetEvent:output_type -> alis.a2a.extension.history.v1.Event
	15, // 53: alis.a2a.extension.history.v1.SessionsService.ListEvents:output_type -> alis.a2a.extension.history.v1.ListEventsResponse
	2,  // 54: alis.a2a.extension.history.v1.SessionsService.StreamEvents:output_type -> alis.a2a.extension.history.v1.Event
	38, // [38:55] is the sub-list for method output_type
	21, // [21:38] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_alis_a2a_extension_history_v1_session_proto_init() }
func file_alis_a2a_extension_history_v1_session_proto_init() {
	if File_alis_a2a_extension_history_v1_session_proto != nil {
		return
	}
	file_alis_a2a_extension_history_v1_a2a_proto_init()
	file_alis_a2a_extension_history_v1_session_proto_msgTypes[2].OneofWrappers = []any{
		(*Event_Task)(nil),
		(*Event_Message)(nil),
		(*Event_StatusUpdate)(nil),
		(*Event_ArtifactUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_a2a_extension_history_v1_session_proto_rawDesc), len(file_alis_a2a_extension_history_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_a2a_extension_history_v1_session_proto_goTypes,
		DependencyIndexes: file_alis_a2a_extension_history_v1_session_proto_depIdxs,
		MessageInfos:      file_alis_a2a_extension_history_v1_session_proto_msgTypes,
	}.Build()
	File_alis_a2a_extension_history_v1_session_proto = out.File
	file_alis_a2a_extension_history_v1_session_proto_goTypes = nil
	file_alis_a2a_extension_history_v1_session_proto_depIdxs = nil
}
