// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/a2a/extension/history/v1/session.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-02-20 13:10:24 UTC

package v1

const (
	// SessionsService_GetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.GetIamPolicy method.
	SessionsService_GetIamPolicy_FullMethodDescription = "Gets the IAM policy for a resource implemented in this service."
	// SessionsService_SetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.SetIamPolicy method.
	SessionsService_SetIamPolicy_FullMethodDescription = "Sets the IAM policy for a resource implemented in this service."
	// SessionsService_TestIamPermissions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.TestIamPermissions method.
	SessionsService_TestIamPermissions_FullMethodDescription = "Returns permissions that a caller has on the specified resource."
	// SessionsService_BatchTestIamPermissions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.BatchTestIamPermissions method.
	SessionsService_BatchTestIamPermissions_FullMethodDescription = "Returns permissions that a caller has on the specified resources."
	// SessionsService_AddIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.AddIamBindings method.
	SessionsService_AddIamBindings_FullMethodDescription = "Adds principals or updates the roles existing principals have on an IAM Policy protected resource."
	// SessionsService_RemoveIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.RemoveIamBindings method.
	SessionsService_RemoveIamBindings_FullMethodDescription = "Removes principals or some of the roles they have on an IAM Policy protected resource."
	// SessionsService_ListSessions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.ListSessions method.
	SessionsService_ListSessions_FullMethodDescription = "Lists all sessions."
	// SessionsService_GetSession_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.GetSession method.
	SessionsService_GetSession_FullMethodDescription = "Gets a session by its resource name."
	// SessionsService_SetSessionDisplayName_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.SetSessionDisplayName method.
	SessionsService_SetSessionDisplayName_FullMethodDescription = "Sets the display name of an existing sessions. Useful if user is not happy with the generated name."
	// SessionsService_DeleteSession_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.DeleteSession method.
	SessionsService_DeleteSession_FullMethodDescription = "Deletes an session."
	// SessionsService_BatchGetSessions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.BatchGetSessions method.
	SessionsService_BatchGetSessions_FullMethodDescription = "Get a batch of sessions by their resource names."
	// SessionsService_BatchDeleteSessions_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.BatchDeleteSessions method.
	SessionsService_BatchDeleteSessions_FullMethodDescription = "Batch deletes sessions."
	// SessionsService_BatchCreateEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.BatchCreateEvents method.
	SessionsService_BatchCreateEvents_FullMethodDescription = "Batch create events"
	// SessionsService_CreateEvent_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.CreateEvent method.
	SessionsService_CreateEvent_FullMethodDescription = "Creates a new event."
	// SessionsService_GetEvent_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.GetEvent method.
	SessionsService_GetEvent_FullMethodDescription = "Gets an event by its resource name."
	// SessionsService_ListEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.ListEvents method.
	SessionsService_ListEvents_FullMethodDescription = "Lists all events."
	// SessionsService_StreamEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.SessionsService.StreamEvents method.
	SessionsService_StreamEvents_FullMethodDescription = "Stream events."
)
