// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: alis/a2a/extension/history/v1/session.proto

package v1

import (
	context "context"
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v11 "open.alis.services/protobuf/alis/open/iam/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionsService_GetIamPolicy_FullMethodName            = "/alis.a2a.extension.history.v1.SessionsService/GetIamPolicy"
	SessionsService_SetIamPolicy_FullMethodName            = "/alis.a2a.extension.history.v1.SessionsService/SetIamPolicy"
	SessionsService_TestIamPermissions_FullMethodName      = "/alis.a2a.extension.history.v1.SessionsService/TestIamPermissions"
	SessionsService_BatchTestIamPermissions_FullMethodName = "/alis.a2a.extension.history.v1.SessionsService/BatchTestIamPermissions"
	SessionsService_AddIamBindings_FullMethodName          = "/alis.a2a.extension.history.v1.SessionsService/AddIamBindings"
	SessionsService_RemoveIamBindings_FullMethodName       = "/alis.a2a.extension.history.v1.SessionsService/RemoveIamBindings"
	SessionsService_ListSessions_FullMethodName            = "/alis.a2a.extension.history.v1.SessionsService/ListSessions"
	SessionsService_GetSession_FullMethodName              = "/alis.a2a.extension.history.v1.SessionsService/GetSession"
	SessionsService_SetSessionDisplayName_FullMethodName   = "/alis.a2a.extension.history.v1.SessionsService/SetSessionDisplayName"
	SessionsService_DeleteSession_FullMethodName           = "/alis.a2a.extension.history.v1.SessionsService/DeleteSession"
	SessionsService_BatchGetSessions_FullMethodName        = "/alis.a2a.extension.history.v1.SessionsService/BatchGetSessions"
	SessionsService_BatchDeleteSessions_FullMethodName     = "/alis.a2a.extension.history.v1.SessionsService/BatchDeleteSessions"
	SessionsService_BatchCreateEvents_FullMethodName       = "/alis.a2a.extension.history.v1.SessionsService/BatchCreateEvents"
	SessionsService_CreateEvent_FullMethodName             = "/alis.a2a.extension.history.v1.SessionsService/CreateEvent"
	SessionsService_GetEvent_FullMethodName                = "/alis.a2a.extension.history.v1.SessionsService/GetEvent"
	SessionsService_ListEvents_FullMethodName              = "/alis.a2a.extension.history.v1.SessionsService/ListEvents"
	SessionsService_StreamEvents_FullMethodName            = "/alis.a2a.extension.history.v1.SessionsService/StreamEvents"
)

// SessionsServiceClient is the client API for SessionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionsService
type SessionsServiceClient interface {
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error)
	// Returns permissions that a caller has on the specified resources.
	BatchTestIamPermissions(ctx context.Context, in *v11.BatchTestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.BatchTestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(ctx context.Context, in *v11.AddIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(ctx context.Context, in *v11.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Lists all sessions.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Gets a session by its resource name.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Sets the display name of an existing sessions. Useful if user is not happy with the generated name.
	SetSessionDisplayName(ctx context.Context, in *SetSessionDisplayNameRequest, opts ...grpc.CallOption) (*Session, error)
	// Deletes an session.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Get a batch of sessions by their resource names.
	BatchGetSessions(ctx context.Context, in *BatchGetSessionsRequest, opts ...grpc.CallOption) (*BatchGetSessionsResponse, error)
	// Batch deletes sessions.
	BatchDeleteSessions(ctx context.Context, in *BatchDeleteSessionsRequest, opts ...grpc.CallOption) (*BatchDeleteSessionsResponse, error)
	// Batch create events
	BatchCreateEvents(ctx context.Context, in *BatchCreateEventsRequest, opts ...grpc.CallOption) (*BatchCreateEventsResponse, error)
	// Creates a new event.
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*Event, error)
	// Gets an event by its resource name.
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error)
	// Lists all events.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Stream events.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type sessionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsServiceClient(cc grpc.ClientConnInterface) SessionsServiceClient {
	return &sessionsServiceClient{cc}
}

func (c *sessionsServiceClient) GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, SessionsService_GetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, SessionsService_SetIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_TestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) BatchTestIamPermissions(ctx context.Context, in *v11.BatchTestIamPermissionsRequest, opts ...grpc.CallOption) (*v11.BatchTestIamPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.BatchTestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_BatchTestIamPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) AddIamBindings(ctx context.Context, in *v11.AddIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, SessionsService_AddIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) RemoveIamBindings(ctx context.Context, in *v11.RemoveIamBindingsRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, SessionsService_RemoveIamBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionsService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) SetSessionDisplayName(ctx context.Context, in *SetSessionDisplayNameRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionsService_SetSessionDisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionsService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) BatchGetSessions(ctx context.Context, in *BatchGetSessionsRequest, opts ...grpc.CallOption) (*BatchGetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_BatchGetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) BatchDeleteSessions(ctx context.Context, in *BatchDeleteSessionsRequest, opts ...grpc.CallOption) (*BatchDeleteSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_BatchDeleteSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) BatchCreateEvents(ctx context.Context, in *BatchCreateEventsRequest, opts ...grpc.CallOption) (*BatchCreateEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateEventsResponse)
	err := c.cc.Invoke(ctx, SessionsService_BatchCreateEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*Event, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Event)
	err := c.cc.Invoke(ctx, SessionsService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Event)
	err := c.cc.Invoke(ctx, SessionsService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionsService_ServiceDesc.Streams[0], SessionsService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionsService_StreamEventsClient = grpc.ServerStreamingClient[Event]

// SessionsServiceServer is the server API for SessionsService service.
// All implementations must embed UnimplementedSessionsServiceServer
// for forward compatibility.
//
// SessionsService
type SessionsServiceServer interface {
	// Gets the IAM policy for a resource implemented in this service.
	GetIamPolicy(context.Context, *v1.GetIamPolicyRequest) (*v1.Policy, error)
	// Sets the IAM policy for a resource implemented in this service.
	SetIamPolicy(context.Context, *v1.SetIamPolicyRequest) (*v1.Policy, error)
	// Returns permissions that a caller has on the specified resource.
	TestIamPermissions(context.Context, *v1.TestIamPermissionsRequest) (*v1.TestIamPermissionsResponse, error)
	// Returns permissions that a caller has on the specified resources.
	BatchTestIamPermissions(context.Context, *v11.BatchTestIamPermissionsRequest) (*v11.BatchTestIamPermissionsResponse, error)
	// Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
	AddIamBindings(context.Context, *v11.AddIamBindingsRequest) (*v1.Policy, error)
	// Removes principals or some of the roles they have on an IAM Policy protected resource.
	RemoveIamBindings(context.Context, *v11.RemoveIamBindingsRequest) (*v1.Policy, error)
	// Lists all sessions.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Gets a session by its resource name.
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	// Sets the display name of an existing sessions. Useful if user is not happy with the generated name.
	SetSessionDisplayName(context.Context, *SetSessionDisplayNameRequest) (*Session, error)
	// Deletes an session.
	DeleteSession(context.Context, *DeleteSessionRequest) (*Session, error)
	// Get a batch of sessions by their resource names.
	BatchGetSessions(context.Context, *BatchGetSessionsRequest) (*BatchGetSessionsResponse, error)
	// Batch deletes sessions.
	BatchDeleteSessions(context.Context, *BatchDeleteSessionsRequest) (*BatchDeleteSessionsResponse, error)
	// Batch create events
	BatchCreateEvents(context.Context, *BatchCreateEventsRequest) (*BatchCreateEventsResponse, error)
	// Creates a new event.
	CreateEvent(context.Context, *CreateEventRequest) (*Event, error)
	// Gets an event by its resource name.
	GetEvent(context.Context, *GetEventRequest) (*Event, error)
	// Lists all events.
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Stream events.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedSessionsServiceServer()
}

// UnimplementedSessionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServiceServer struct{}

func (UnimplementedSessionsServiceServer) GetIamPolicy(context.Context, *v1.GetIamPolicyRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedSessionsServiceServer) SetIamPolicy(context.Context, *v1.SetIamPolicyRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedSessionsServiceServer) TestIamPermissions(context.Context, *v1.TestIamPermissionsRequest) (*v1.TestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestIamPermissions not implemented")
}
func (UnimplementedSessionsServiceServer) BatchTestIamPermissions(context.Context, *v11.BatchTestIamPermissionsRequest) (*v11.BatchTestIamPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchTestIamPermissions not implemented")
}
func (UnimplementedSessionsServiceServer) AddIamBindings(context.Context, *v11.AddIamBindingsRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIamBindings not implemented")
}
func (UnimplementedSessionsServiceServer) RemoveIamBindings(context.Context, *v11.RemoveIamBindingsRequest) (*v1.Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIamBindings not implemented")
}
func (UnimplementedSessionsServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionsServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionsServiceServer) SetSessionDisplayName(context.Context, *SetSessionDisplayNameRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSessionDisplayName not implemented")
}
func (UnimplementedSessionsServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionsServiceServer) BatchGetSessions(context.Context, *BatchGetSessionsRequest) (*BatchGetSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetSessions not implemented")
}
func (UnimplementedSessionsServiceServer) BatchDeleteSessions(context.Context, *BatchDeleteSessionsRequest) (*BatchDeleteSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteSessions not implemented")
}
func (UnimplementedSessionsServiceServer) BatchCreateEvents(context.Context, *BatchCreateEventsRequest) (*BatchCreateEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateEvents not implemented")
}
func (UnimplementedSessionsServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*Event, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedSessionsServiceServer) GetEvent(context.Context, *GetEventRequest) (*Event, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedSessionsServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedSessionsServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedSessionsServiceServer) mustEmbedUnimplementedSessionsServiceServer() {}
func (UnimplementedSessionsServiceServer) testEmbeddedByValue()                         {}

// UnsafeSessionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServiceServer will
// result in compilation errors.
type UnsafeSessionsServiceServer interface {
	mustEmbedUnimplementedSessionsServiceServer()
}

func RegisterSessionsServiceServer(s grpc.ServiceRegistrar, srv SessionsServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionsService_ServiceDesc, srv)
}

func _SessionsService_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetIamPolicy(ctx, req.(*v1.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).SetIamPolicy(ctx, req.(*v1.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).TestIamPermissions(ctx, req.(*v1.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_BatchTestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.BatchTestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).BatchTestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_BatchTestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).BatchTestIamPermissions(ctx, req.(*v11.BatchTestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_AddIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.AddIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).AddIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_AddIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).AddIamBindings(ctx, req.(*v11.AddIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_RemoveIamBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.RemoveIamBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).RemoveIamBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_RemoveIamBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).RemoveIamBindings(ctx, req.(*v11.RemoveIamBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_SetSessionDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSessionDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).SetSessionDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_SetSessionDisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).SetSessionDisplayName(ctx, req.(*SetSessionDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_BatchGetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).BatchGetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_BatchGetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).BatchGetSessions(ctx, req.(*BatchGetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_BatchDeleteSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).BatchDeleteSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_BatchDeleteSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).BatchDeleteSessions(ctx, req.(*BatchDeleteSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_BatchCreateEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).BatchCreateEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_BatchCreateEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).BatchCreateEvents(ctx, req.(*BatchCreateEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionsService_StreamEventsServer = grpc.ServerStreamingServer[Event]

// SessionsService_ServiceDesc is the grpc.ServiceDesc for SessionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.a2a.extension.history.v1.SessionsService",
	HandlerType: (*SessionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIamPolicy",
			Handler:    _SessionsService_GetIamPolicy_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _SessionsService_SetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _SessionsService_TestIamPermissions_Handler,
		},
		{
			MethodName: "BatchTestIamPermissions",
			Handler:    _SessionsService_BatchTestIamPermissions_Handler,
		},
		{
			MethodName: "AddIamBindings",
			Handler:    _SessionsService_AddIamBindings_Handler,
		},
		{
			MethodName: "RemoveIamBindings",
			Handler:    _SessionsService_RemoveIamBindings_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SessionsService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionsService_GetSession_Handler,
		},
		{
			MethodName: "SetSessionDisplayName",
			Handler:    _SessionsService_SetSessionDisplayName_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionsService_DeleteSession_Handler,
		},
		{
			MethodName: "BatchGetSessions",
			Handler:    _SessionsService_BatchGetSessions_Handler,
		},
		{
			MethodName: "BatchDeleteSessions",
			Handler:    _SessionsService_BatchDeleteSessions_Handler,
		},
		{
			MethodName: "BatchCreateEvents",
			Handler:    _SessionsService_BatchCreateEvents_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _SessionsService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _SessionsService_GetEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _SessionsService_ListEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _SessionsService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "alis/a2a/extension/history/v1/session.proto",
}
